// <auto-generated />
using MVCAssignments.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCAssignments.Migrations
{
    [DbContext(typeof(MVCAssignmentsContext))]
    [Migration("20220217101743_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCAssignments.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            CountryId = 1000,
                            Name = "Stockholm"
                        },
                        new
                        {
                            Id = 1001,
                            CountryId = 1001,
                            Name = "Helsingfors"
                        },
                        new
                        {
                            Id = 1002,
                            CountryId = 1002,
                            Name = "Reykjavík"
                        },
                        new
                        {
                            Id = 1003,
                            CountryId = 1003,
                            Name = "Köpenhamn"
                        },
                        new
                        {
                            Id = 1004,
                            CountryId = 1004,
                            Name = "Oslo"
                        });
                });

            modelBuilder.Entity("MVCAssignments.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Name = "Sverige"
                        },
                        new
                        {
                            Id = 1001,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 1002,
                            Name = "Island"
                        },
                        new
                        {
                            Id = 1003,
                            Name = "Danmark"
                        },
                        new
                        {
                            Id = 1004,
                            Name = "Norge"
                        });
                });

            modelBuilder.Entity("MVCAssignments.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            CityId = 1000,
                            Name = "Sven Svensk",
                            Phone = "1111111111"
                        },
                        new
                        {
                            Id = 1001,
                            CityId = 1001,
                            Name = "Pecka Finsk",
                            Phone = "2222222222"
                        },
                        new
                        {
                            Id = 1002,
                            CityId = 1002,
                            Name = "Sigurður Isländsk",
                            Phone = "3333333333"
                        },
                        new
                        {
                            Id = 1003,
                            CityId = 1003,
                            Name = "Preben Dansk",
                            Phone = "4444444444"
                        },
                        new
                        {
                            Id = 1004,
                            CityId = 1004,
                            Name = "Ola Norman",
                            Phone = "5555555555"
                        });
                });

            modelBuilder.Entity("MVCAssignments.Models.City", b =>
                {
                    b.HasOne("MVCAssignments.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVCAssignments.Models.Person", b =>
                {
                    b.HasOne("MVCAssignments.Models.City", "City")
                        .WithMany("People")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
